### ISSUE TITLE
the tool does not work on mac os

### ISSUE THREAD

**Issue by tingsu** [reverse-unina/AndroidRipper#18]
Thanks for developing this tool. I strictly followed the steps in the wiki. But the tool does not work.

When execute the command "java -jar AndroidRipperInstaller.jar":
  
I got these exception:

     Android Ripper Installer
Using default configuration file 'ripper.properties'!
Starting installation...
java.io.IOException: Cannot run program "android.bat": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at it.unina.android.ripper.installer.console.GuiRipperInstaller.validateCommand(GuiRipperInstaller.java:378)
	at it.unina.android.ripper.installer.console.GuiRipperInstaller.install(GuiRipperInstaller.java:74)
	at it.unina.android.ripper.installer.console.GuiRipperInstallerMain.main(GuiRipperInstallerMain.java:29)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 6 more
java.io.IOException: Cannot run program "ant.bat": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at it.unina.android.ripper.installer.console.GuiRipperInstaller.validateCommand(GuiRipperInstaller.java:378)
	at it.unina.android.ripper.installer.console.GuiRipperInstaller.install(GuiRipperInstaller.java:80)
	at it.unina.android.ripper.installer.console.GuiRipperInstallerMain.main(GuiRipperInstallerMain.java:29)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 6 more
[1468898788722] Booting Emulator!
[1468898788725] Waiting for Emulator...

In addition, where can I get the app model?

Hope to get your help. Thanks!

Ting

**Comment by tingsu** [comment]
The tool can be finally ran for apps, despite the exceptions still appear.
