### ISSUE TITLE
 Config file does not exist!

### ISSUE THREAD

**Issue by DAN931223** [reverse-unina/AndroidRipper#7]
To launch Android Ripper from the command line:java -jar AndroidRipper.jar apkFile [config.properties]
For example,To launch Android Ripper from the command line:java -jar AndroidRipper.jar E:\GuiRipper\AndroidRipper-2017.10\tool\tools\AndroidRipperService.apk [default.properties]
Error message:
ERROR: Config file does not exist!
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at it.unina.android.ripper.boundary.AndroidRipper.main(AndroidRipper.java:80)
        ... 5 more
I need help badly, thank you very much!

**Comment by LeoLRH** [comment]
@DAN931223 Hi, have you run this tool successfully? To many errors

**Comment by nstdr531** [comment]
@DAN931223 @LeoLRH Hi, have you run this tool successfully?
